### ISSUE TITLE
Hey there @renzo-caroca

### ISSUE THREAD

**Issue by jitteryorange** [xavier150/Blender-For-UnrealEngine-Addons#128]
am having a similar issue but with the latest version...what am i doing wrong?
![2021-09-26_15-04-38_Moment](https://user-images.githubusercontent.com/54306298/134822591-208174fe-d90f-4019-8d96-31fd7c6986ce.jpg)

**Comment by xavier150** [comment]
Hey @jitteryorange
Thanks for the report and sorry for the delay.
That look like this issue https://github.com/xavier150/Blender-For-UnrealEngine-Addons/issues/127. I fixed in the last Dev Branch: [Download and installation from dev Branch](https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch) You can try it ?
If that don't work you can send me the file? I will try to found what wrong.

**Comment by xavier150** [comment]
Hello, you still have issues?
