### ISSUE TITLE
"Acess denied"

### ISSUE THREAD

**Issue by LucianoDaluz** [xavier150/Blender-For-UnrealEngine-Addons#140]
Hi just trying to do a simple export to UE and I got this message "Acess Denied", nothing is exported and it just duplicate the mesh inside Blender (?)
![image](https://user-images.githubusercontent.com/94625454/142451603-cc8a760d-5ec8-4dca-9b7f-1b510252324c.png)
![image](https://user-images.githubusercontent.com/94625454/142451665-de09312b-b432-40c9-8aa8-58c8f832c396.png)
![image](https://user-images.githubusercontent.com/94625454/142451835-491ad748-fab0-474c-82cf-c3b3bf7e41a6.png)

**Comment by xavier150** [comment]
Hello @LucianoDaluz,
Thanks for the report, a bug remove the ":" So the addon try to export the file in "C\Users" and not in "C:\Users"
The mesh was duplicated because the export was not finished when you get the error.

I fixed in the new pre release you can try it? 
https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/vp0.3.1

**Comment by LucianoDaluz** [comment]
Testing here and it works now! Testing here. Thanks
