### ISSUE TITLE
wrong transform with MMD camera.

### ISSUE THREAD

**Issue by iJzFan** [xavier150/Blender-For-UnrealEngine-Addons#161]
Hi, I am trying use this addons to convert MMD Camera to UE. Some of the frames will have wrong transform.

![image](https://user-images.githubusercontent.com/26226559/186239195-35401b8e-fb16-4745-996f-52779de6967f.png)
P1 was the frames 586 location & rotation showed in blender.

![image](https://user-images.githubusercontent.com/26226559/186239435-5f1a7d63-cc6e-4f15-93db-e05e1c7bf51d.png)
P2 was the frames 586 location & rotation imported by Copy import script(Sequencer) which was wrong.

![image](https://user-images.githubusercontent.com/26226559/186239737-512d9dd9-a734-4239-b920-b5757d131299.png)
P3 was the frames 586 location & rotation copy by Copy Cine Cameras for Unreal which was right.

I also attached the blender files as below.
[wrong_camera_after_frame_586.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/9409725/wrong_camera_after_frame_586.zip)

**Comment by xavier150** [comment]
Hello @iJzFan Thanks for the report!
This is because your camera do extreme rotation movement in one frame. By addon try to fix axis flippings but extrem rotation movement in one frame will break it. I added an option for disable it and so it Fix the Issue.
![image](https://user-images.githubusercontent.com/7216958/210791644-d9ccddab-f6fa-4ee9-adab-11b1b1afd630.png)
You can try the last dev branch here: https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch

But the best is would be to have multiple camera in your Blender scene and use Markers to camera switch
https://docs.blender.org/manual/en/dev/animation/markers.html#bind-camera-to-marker and so avoid extreme movement in one frame

**Comment by xavier150** [comment]
If all good I will close this issue after 0.4.0 update release.

**Comment by iJzFan** [comment]
Yes, it fixed my issue. Thanks!
