### ISSUE TITLE
Python script not importing animations

### ISSUE THREAD

**Issue by isthisamug** [xavier150/Blender-For-UnrealEngine-Addons#179]
Hello, thank you for making the Blender-> UE5 pipeline so much less of a pain, and thank you for making this a free product.

When I use the console command to import the files created from the plugin, it imports everything BUT the animations. They are indeed created, and visible within ExportedFbx/SkeletalMesh/metarig/Anim . I am able to import them (so this is not a critical problem in any regard) by manually dragging the animations from /Anim into the UE5 filesystem, but I don't think that's what you intended for the user to do. 

Regardless, thank you for saving me from the last few hours of pain with this amazing solution.

**Comment by xavier150** [comment]
Hello @caydenbullock !
Thanks and sorry I just see your message.
I think this issue was fix in the last dev branch in version 0.4.2. [Dev Branch](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/wiki/Download-And-Installation#download-and-installation-from-dev-branch)
Look about "Download and installation from dev Branch". After install restart Blender and try again.

If that don't work send me the blender file so I will able to try on my side.

**Comment by xavier150** [comment]
I released 0.4.2 and 0.4.3 so I close this issue
