### ISSUE TITLE
[Blender 2.8] Instance support and "bone size too small to create physics asset" during import

### ISSUE THREAD

**Issue by dafred94** [xavier150/Blender-For-UnrealEngine-Addons#24]
Hi, I would like to import my simple hoverboard model using this script.. However, I can't get it to work. 
[hoverboard.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/3457012/hoverboard.zip)
I am making use of modifiers and instances and the script seems to not like this. Which would be the correct way to export my model including the armature?

**Comment by xavier150** [comment]
Hey dafred94,
Thanks for the feedback !

Currently the collection is not working yet, it's a planned thing for the next version https://trello.com/c/P2hjPAdZ/38-blender-for-unreal-engine-addon-24

I'm sending you a temporary version if you can not do without the collections 
[blender-for-unrealengine - 2.8_temp.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/3457351/blender-for-unrealengine.-.2.8_temp.zip) #Temp 0.2.4

- The skeletal mesh will be exported but it has children who will be exported as static meshes so at each export you will have some un-desired offset.
- "R_tire" mesh use negative scale so he will have fliped faces in Unreal
- "Base" mesh have flipped faces
- With skeletal mesh the Empty work good but are not valid children because they're not vertex groups
- In Unreal the Skeletal Mesh are exported with only one wheel. I have the feeling that Unreal is struggling to differentiate Blender collection in FBX File. I will try to fix this too in the next version.



[hoverboard_edited.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/3457511/hoverboard_edited.zip)

(Sorry for my english)

**Comment by dafred94** [comment]
Thank you very much for your quick response (in comparison to mine..). I'm not completely sure how to use the .blend file you provided, but using your tip to get rid of the collections (and, in my case, applying any delta transforms, modifiers, recalculating normals and "making instances real"), I was able to export the mesh as expected in separate objects (some other tutorials suggest a single mesh with weight paint). Might you consider incorporating this workflow (which has to be repeated any time I make a small change to my model..) into your export script? I guess it might work well with a temporary duplicate that is deleted again after the export.

Thank You for Your awesome export plugin so far!

**Comment by xavier150** [comment]
Hey dafred94, thanks and yeah is something I'm anticipating, apply modifiers before exporting and all data, this will help manage instances and collection

**Comment by xavier150** [comment]
Hey dafred94,
I published new update ! Your Issue should be solved now https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/latest
