### ISSUE TITLE
[Blender 2.8,Unreal Engine 4.22] - Daz Studio Bone Issues

### ISSUE THREAD

**Issue by Hopefullyidontgetbanned** [xavier150/Blender-For-UnrealEngine-Addons#26]
![Screenshot (766)](https://user-images.githubusercontent.com/45346421/62594791-a97f3b80-b890-11e9-832d-ad268a7e623f.png)
![Screenshot (767)](https://user-images.githubusercontent.com/45346421/62594807-c0259280-b890-11e9-8d06-efc394f59701.png)

Used the Daz Studio Import Plugin and it works well in blender but Plugin Doesn't See the Multiple Bone Roots as an Issue. The Duplicate Bone Names can likely be automated too since you could find increment their names like bonename_001 or something like that

**Comment by xavier150** [comment]
Hello Hope !
I here now, "Plugin Doesn't See the Multiple Bone Roots" you wan say in My addon ? Normally this should be detected as a potential error

To correct multiple root you can add a new root bone and set the others root as child of the new root bone
About the duplicate bone name I think it's a error

Can you send me the file ? xavierloux.loux@gmail.com I will try to found the problem

**Comment by koticR** [comment]
This is not a problem with the addon.
You've exported your character from DAZ without checking the flag 'Merge Clothing Into Figure Skeleton' which is necessary otherwise you'll end with multiple identical rigs. 

You can try to export the character itself (Genesis 8 Female) without the clothing parts, that should technically get the character into the engine. After that you can export the clothing parts **one by one** and use the existing Gen8 rig inside the UE4 (The one that has been created after you imported the Character). 

Fair warning before you waste your time. The DAZ characters & rig might look fine after import but it's a nightmare to work with. A few things to note about DAZ characters and the UE4.

- The UE4 does not support Quaternion (Take a look at twist bones). You may be able to convert the rig from Quaternion to Linear Interpolation inside DAZ (Edit -> Figure -> Rigging -> One of the settings there maybe). 
- Without adjusting the bone names and hierarchy inside DAZ itself you will most likely not get any root motions or general animations to work. In DAZ open the Joint Editor and start from there, google how to work with that abomination since it's messy and hard to explain properly.
- The Eyes will not work properly due to the additional 'EyeMoisture' mesh, again you might be able to delete it in DAZ but i'm not sure since i never bothered using it. 
- The material setup is a massive waste of draw calls. It comes with 16 slots but you can boil it down to 8 if you merge Surface-Groups who are on the same UV island (Fingernails to Arms, Toenails to Legs, Ears - EyeSocket - Lips to Face etc.). 
- Quite a few textures that come with certain DAZ figures are in JPG format and have compression artifacts.

The reason why i said to fix most problems in DAZ instead of Blender or any other DCC is that this seems to be the only way to keep most things intact (morphs, poses, animations etc.) 
My honest opinion is to scrap DAZ and hire a character artist, you get a lot more control over the final character compared to what you get for that atrocious Interactive License price.

**Comment by Hopefullyidontgetbanned** [comment]
okay i see.
