### ISSUE TITLE
Possibility to set custom presets for the export options

### ISSUE THREAD

**Issue by NazzarenoGiannelli** [xavier150/Blender-For-UnrealEngine-Addons#27]
First of all thanks a million times for this awesome addon.

What would be really helpful in my case is the opportunity to save presets of the export options or to be able to assign the option to multiple objects at a time.
90% of the time I export just static meshes, Y forward, Z up at 128 of lightmap resolution.
It's tedious to have to put all these values for each mesh.
Maybe it's already possible. Am I doing something wrong utilizing the addon?

**Comment by xavier150** [comment]
Hey Nazzareno,
That right ! I noted for the next version

**Comment by NazzarenoGiannelli** [comment]
@xavier150 Sweet! Thanks 🙂

**Comment by xavier150** [comment]
Hey Nazzareno,
I published new update ! Your Issue should be solved now https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/latest
You can chose a presets for object global properties

**Comment by gulbeykasap** [comment]
Thanks again for creating a reliable, fast pipeline. I didn't want to open up a new issue since it's somehow related to this.

I'm using this plugin to easily export character animations and meshes. Most of the time I need to uncheck skeletal mesh while exporting character animations so it gives me only the skeleton(without the mesh). The resulting fbx size is much smaller as you don't need to include mesh inside animation files again.

Setting up global properties presets are working fine on upper levels but they don't change the export options down below. They stay the same regardless of presets. Could you also include saving them as well?

[Screenshot](https://imgur.com/AQpdWg5)

**Comment by xavier150** [comment]
Hi gulbeykasap,
I can add this but is this something that can really help? 
In general it is just check boxes to define what should be exported. Not really a configuration that must repeat on several files

**Comment by xavier150** [comment]
Hey @gulbeykasap I published the new [update 0.2.8](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/v0.2.8) 
![image](https://user-images.githubusercontent.com/7216958/110948148-49d8f400-8341-11eb-8670-e1f88995361e.png)

I updated the UI and this can help you so I close this issue :) You can create a new issue if you need
