### ISSUE TITLE
Rotation Pretty Bad

### ISSUE THREAD

**Issue by SaberhagenIndustries** [xavier150/Blender-For-UnrealEngine-Addons#57]
So given that the Blender Front Orthographic View wants you to align your model to -Y that is how I model my characters. With the default export settings of -Z Forward and Y Up this results in the character facing Y Forward in Unreal if you have the Convert Scene option turned on, and the root bone has a z rotation of -180. With Convert Scene off the character faces -Y Up and Z Forward which is exactly the reverse of the actually selected axis and the rotation of the root bone has an additional 90 on x. This kind of already shows that there is a significant problem in how the model gets rotated because for a correct facing I would expect that I set the export up to X Forward and Z Up, since that is what Unreal has...  when turning convert on that results in the exact same Y Forward and -180 on the root, without it we are actually getting somewhere because the model faces -X Forward and Z Up with  Z -90 rotation on the root bone. That is still facing the wrong way which is very very weird. Going -X Forward on export settings finally faces the model the correct way of Unreal X Forward with the only problem being a remaining rotation of Z 90 on the root bone ... which is still better than -180 and facing the wrong way. 

It would be nice to get that to actually work correctly, because this plugin is the first that actually fixed the scaling issues :>

**Comment by xavier150** [comment]
Hello Saberhagen! sorry for the delay.

Your export setting is good but In Blender your character should facing Y Backward and in the import settings of unreal you should check Convert Scene option.
![ExportAxes](https://user-images.githubusercontent.com/7216958/83969672-9b93b000-a8d1-11ea-828a-a35f0680111e.png)

To avoid all problem the best is this settings in the screen with the unit scale at 0.01 in Blender scene. This is due because Unreal and Blender do not use the same axes and scale.
