### ISSUE TITLE
Shape keys with Drivers' f-curves are imported differently into Unreal Engine 4

### ISSUE THREAD

**Issue by zkm1** [xavier150/Blender-For-UnrealEngine-Addons#62]
I'm not sure if this is a bug or a missing feature or a user error on my part, but whenever I import shape-keys animated using drivers, their f-curves in Unreal Engine 4 differ than when I exported them in blender.

This is my f-curves in blender. It is all green because I only made the local Y axis affecting the shapekeys. The curves are smoother and bezier-like
![image](https://user-images.githubusercontent.com/10038200/86541956-375f0e80-bec6-11ea-9ab0-2ccea3d439b2.png)

Exporting from Blender process:
1. Select the armature
2. Select Export-Recursively
3. Leave all other settings as is
4. Make sure the action is selected for export
5. Pressed export to Unreal Engine 4

These are the same curves inside Unreal Engine 4, they become a mix between constant and linear interpolation rather than the smooth curves from my previous image.
![image](https://user-images.githubusercontent.com/10038200/86541980-53fb4680-bec6-11ea-84b1-c6c6ae24c271.png)

Importing to Unreal Engine 4 process:

1. Imported by clicking the .fbx file
2. Followed the instructions from the documentation

**Comment by xavier150** [comment]
Hello zkm1,
Oh that weird, you can send me the file ? I will try to found what wrong

**Comment by zkm1** [comment]
Ok,

I have sent it to your email.

**Comment by xavier150** [comment]
Thanks I tested and found the problem! Since you are using the scene unit scale at 1 my addon rescale your character for UE4 and the shape keys are 100 times too big. That now fixed:

![Blender Unreal Shape key](https://user-images.githubusercontent.com/7216958/86548335-4c768480-bf3c-11ea-8746-7b73f8864273.png)

I think publish the release version 0.2.7.3 tomorrow. Here is the beta build to correct this: [blender-for-unrealengine - 2.8.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/4876391/blender-for-unrealengine.-.2.8.zip)

**Comment by zkm1** [comment]
Wow it works now! Thanks alot!
