### ISSUE TITLE
Feature Request: Add support for FBX LOD group import

### ISSUE THREAD

**Issue by bkmeneguello** [xavier150/Blender-For-UnrealEngine-Addons#64]
Instead of require UnrealEnginePython to import LOD, it could make use of UE4 LODGroup import ([FbxMainImport.cpp#L778](https://github.com/EpicGames/UnrealEngine/blob/f8f4b403eb682ffc055613c7caf9d2ba5df7f319/Engine/Source/Editor/UnrealEd/Private/Fbx/FbxMainImport.cpp#L778)), it only requires a parent node (can be an empty) with a property `fbx_type=LodGroup` and each child with name like `LOD_<name><0-7>` ([FbxMainImport.cpp#L2134](https://github.com/EpicGames/UnrealEngine/blob/f8f4b403eb682ffc055613c7caf9d2ba5df7f319/Engine/Source/Editor/UnrealEd/Private/Fbx/FbxMainImport.cpp#L2134))

**Comment by xavier150** [comment]
Hello bkmenguello!
LOD import alredy work without UnrealEnginePython since Rev 0.2.7 forget to remove this note in documentation "This works only on StaticMesh with importing via UnrealEnginePython."

For lod I used another method but I will look into this solution which will probably be cleaner.
Btw I will remove UnrealEnginePython integration in Rev 0.2.8
