### ISSUE TITLE
Camera additional tracks  other than the camera transform have not been exported.

### ISSUE THREAD

**Issue by grimask4496** [xavier150/Blender-For-UnrealEngine-Addons#76]
Hello, Thank you for great plugin!
 I have an issue about exporting camera. I cannot export camera additional tracks like Focal length.
I'm using Blender 2.9.0 and plugin ver 2.7.4(latest).

This is my .blend file for testing.
 https://drive.google.com/file/d/1s30CQgu7yzbprwa5ARfcoNGNjkGyPIHa/view?usp=sharing

This is exported .ini file.
https://drive.google.com/file/d/1jyF1f7GstSpOy8i9Zy0THrZBIrc88vlQ/view?usp=sharing

**Comment by xavier150** [comment]
Hello @grimask4496 
Thanks for the report! I just fixed and updated the source files, https://github.com/xavier150/Blender-For-UnrealEngine-Addons/blob/master/README.md#download-and-installation-from-sources

This will be included in the next version 0.2.8. Can you confirm to me that working good with the sources files?

**Comment by grimask4496** [comment]
Hello @xavier150 

I checked it, certainly , additional tracks exported. 
But, maybe 
It should be exported like
UE4FocalLength= BlenderFocalLength*2/3
For example, When in Blenderfocallegth is 24, UE4FocalLength is about 16.
But, now  Blender focal length is exported as it is.

**Comment by xavier150** [comment]
Oh, I will test this tonight and update the sources again

Le mer. 25 nov. 2020 à 07:15, grimask4496 <notifications@github.com> a
écrit :

**Comment by xavier150** [comment]
@grimask4496 I found what wrong, In Unreal Camera Settings you need set Sensor Width and Height like Blender.
By default 36,0 for Width and 24,0 for Height.

I think this has been modified since. So I will add this parameters in additional tracks in the next version. I will update the sources tonight. (In 10 hours for me)

![jNmSx7p](https://user-images.githubusercontent.com/7216958/100327996-49a02d00-2fcc-11eb-8a9e-67578cf34e89.png)
![Tmvrv4a](https://user-images.githubusercontent.com/7216958/100328001-4c9b1d80-2fcc-11eb-80ac-c2074fa1a60d.png)

**Comment by grimask4496** [comment]
Hello @xavier150
OK! I'm glad I knew the cause! I'm looking forward to the update.
Thank you!

**Comment by xavier150** [comment]
Hello @grimask4496 Thank you for your patience,
I just updated the source files, can you tell me if that work good this time ?

**Comment by grimask4496** [comment]
Hello @xavier150 

I've checked the update now. It works! Thank you!
![Test](https://user-images.githubusercontent.com/34054236/100440288-020ec380-30e8-11eb-9f07-b1fefe1045ae.png)

**Comment by xavier150** [comment]
Happy to hear ^^
