### ISSUE TITLE
Extra root bone

### ISSUE THREAD

**Issue by sirmaxim** [xavier150/Blender-For-UnrealEngine-Addons#9]
So, I'm attempting to get an *existing* armature from the ARK: Survival Evolved DevKit to work with this, though I seem to be running into the dreaded extra root bone issue (armature becomes root bone), even when importing it to UE4.21 this happens. If I remove the root bone, I end up with broken animations and wights. Due to the target, I cannot use the import script as plugin support is basically broken in the ADK.

This works great if your content originates entirely from blender, but this issue makes it difficult to work with other sources and teams.

**Comment by xavier150** [comment]
Hi sirmaxim !
With the Rev 0.2.2b https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/v.0.2.2b
The all skeletal mesh are exported with the root bone named as Armature for be skiped in Unreal but this do problems with the animations. So I removed this in Rev 0.2.2c
https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/v.0.2.2c

Maybe in your case this can help you
For the next version I will add an option so that users can choose if they want to delete or not
