### ISSUE TITLE
Keyframe different after export from Blender to Ue in 25fps

### ISSUE THREAD

**Issue by darkprince334455** [xavier150/Blender-For-UnrealEngine-Addons#91]
Mismatch and missing keyframe after exporting to UE

![BlenderCapture](https://user-images.githubusercontent.com/56534459/115495666-bdecad00-a29a-11eb-8c2c-d7b73b0206fa.PNG)

![UeCapture](https://user-images.githubusercontent.com/56534459/115495687-cba23280-a29a-11eb-8e84-7d1a6b8e1c2e.PNG)

**Comment by xavier150** [comment]
Hello!
You speak about a skeletal mesh? You can send mes the model? xavierloux.loux@gmail.com I will try to found what wrong.

**Comment by darkprince334455** [comment]
its the camera from blender to ue4

**Comment by xavier150** [comment]
Hey @darkprince334455 
Thanks for your patience! I was able to reproduce the bug and I found what wrong. I used time in second for place the frame keys but Unreal don't round the value. So when the script place a key at 1.16s so at the frame 28.99999999~ unreal place the key at the frame 28 Instead of 29.

I now use the frame directly and now it works. I published a pre release with the fix: https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/vp0.2.9.1

You can close this issue if all work good now.

**Comment by darkprince334455** [comment]
Hi xavier

Thanks for the quick fix. I've tried the new fix that you provide and it seems that the issue on my end no longer appears. Thank you so much. I will post up a new issue if something else arises.
